workflows:
  gwa-ios:
    name: Golden WebView iOS
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Prepare Flutter project
        script: |
          rm -rf app || true
          flutter create app
          cd app
          flutter pub add webview_flutter
          # ...
      - name: Build iOS IPA
        script: |
          cd app
          flutter build ipa --release
    artifacts:
      - app/build/ios/ipa/*.ipa
    # publishing: (تم التعطيل)
