workflows:
  gwa-android-build:
    name: GWA Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      groups:
        - gwa_config
        - gwa_keystore
      vars:
        GWA_APP_NAME: "Golden WebView App"
        GWA_SITE_URL: "https://example.com"
        GWA_APP_ID: "com.golden.webview.app"
        GWA_THEME_COLOR: "#2196F3"
    
    scripts:
      - name: Set up keystore
        script: |
          if [ -n "$CM_KEYSTORE" ]; then
            echo "Setting up release keystore..."
            echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.jks
            export CM_KEYSTORE_PATH=/tmp/keystore.jks
            echo "Keystore created at /tmp/keystore.jks"
          else
            echo "No keystore configured, will use debug signing"
          fi
      
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      
      - name: Update app configuration
        script: |
          # Update app_config.json with environment variables
          cat > assets/config/app_config.json << EOF
          {
            "app_name": "${GWA_APP_NAME:-Golden WebView App}",
            "site_url": "${GWA_SITE_URL}",
            "app_id": "${GWA_APP_ID:-com.golden.webview.app}",
            "user_agent": "${GWA_USER_AGENT:-}",
            "theme_color": "${GWA_THEME_COLOR:-#2196F3}",
            "orientation": "${GWA_PLATFORM_ORIENTATION:-system}",
            "splash_bg_mode": "${GWA_SPLASH_BG_MODE:-color}",
            "splash_bg_color": "${GWA_SPLASH_BG_COLOR:-#2196F3}",
            "splash_tagline": "${GWA_SPLASH_TAGLINE:-}",
            "splash_text_theme": "${GWA_SPLASH_TEXT_THEME:-light}",
            "splash_delay": ${GWA_SPLASH_DELAY:-3},
            "splash_display_logo": ${GWA_SPLASH_DISPLAY_LOGO:-true},
            "splash_background_image": "${GWA_SPLASH_BACKGROUND_IMAGE_URL:-}",
            "splash_logo_image": "${GWA_SPLASH_LOGO_IMAGE_URL:-}",
            "nav_type": "${GWA_NAV_TYPE:-classic}",
            "nav_items": [],
            "permissions": {
              "geolocation": ${GWA_PERM_GEOLOCATION:-false},
              "camera": ${GWA_PERM_CAMERA:-false},
              "microphone": ${GWA_PERM_MICROPHONE:-false}
            },
            "pull_to_refresh": true,
            "enable_javascript": true,
            "clear_cache_on_start": false
          }
          EOF
          
          echo "Updated app_config.json:"
          cat assets/config/app_config.json
      
      - name: Update Android app ID
        script: |
          APP_ID="${GWA_APP_ID:-com.golden.webview.app}"
          sed -i '' "s/applicationId \".*\"/applicationId \"$APP_ID\"/" android/app/build.gradle
          sed -i '' "s/namespace \".*\"/namespace \"$APP_ID\"/" android/app/build.gradle
          
          # Update package name in Kotlin file
          KOTLIN_DIR="android/app/src/main/kotlin/$(echo $APP_ID | tr '.' '/')"
          mkdir -p "$KOTLIN_DIR"
          echo "package $APP_ID" > "$KOTLIN_DIR/MainActivity.kt"
          echo "" >> "$KOTLIN_DIR/MainActivity.kt"
          echo "import io.flutter.embedding.android.FlutterActivity" >> "$KOTLIN_DIR/MainActivity.kt"
          echo "" >> "$KOTLIN_DIR/MainActivity.kt"
          echo "class MainActivity: FlutterActivity()" >> "$KOTLIN_DIR/MainActivity.kt"
      
      - name: Update Android app name
        script: |
          APP_NAME="${GWA_APP_NAME:-Golden WebView App}"
          echo "<?xml version=\"1.0\" encoding=\"utf-8\"?><resources><string name=\"app_name\">$APP_NAME</string></resources>" > android/app/src/main/res/values/strings.xml
      
      - name: Configure app icon
        script: |
          mkdir -p assets/icon assets/splash
          if [ -n "$GWA_ICON_URL" ] && [ "$GWA_ICON_URL" != "null" ] && [ "$GWA_ICON_URL" != "" ]; then
            echo "Downloading icon from: $GWA_ICON_URL"
            if curl -L "$GWA_ICON_URL" -o assets/icon/app_icon.png --fail --silent --show-error --connect-timeout 30; then
              if [ -f assets/icon/app_icon.png ] && [ -s assets/icon/app_icon.png ]; then
                echo "Icon downloaded successfully"
                echo "" >> pubspec.yaml
                echo "flutter_launcher_icons:" >> pubspec.yaml
                echo "  android: true" >> pubspec.yaml
                echo "  ios: false" >> pubspec.yaml
                echo "  image_path: \"assets/icon/app_icon.png\"" >> pubspec.yaml
                flutter pub get
                flutter pub run flutter_launcher_icons
              else
                echo "Icon file is empty or not created, skipping"
              fi
            else
              echo "Failed to download icon, skipping icon configuration"
            fi
          else
            echo "No icon URL provided, skipping icon configuration"
          fi
      
      - name: Configure splash screen
        script: |
          if [ -n "$GWA_SPLASH_URL" ] && [ "$GWA_SPLASH_URL" != "null" ] && [ "$GWA_SPLASH_URL" != "" ]; then
            echo "Downloading splash from: $GWA_SPLASH_URL"
            if curl -L "$GWA_SPLASH_URL" -o assets/splash/splash.png --fail --silent --show-error --connect-timeout 30; then
              if [ -f assets/splash/splash.png ] && [ -s assets/splash/splash.png ]; then
                echo "Splash downloaded successfully"
                echo "" >> pubspec.yaml
                echo "flutter_native_splash:" >> pubspec.yaml
                echo "  color: \"#ffffff\"" >> pubspec.yaml
                echo "  image: assets/splash/splash.png" >> pubspec.yaml
                echo "  android: true" >> pubspec.yaml
                echo "  ios: false" >> pubspec.yaml
                flutter pub get
                dart run flutter_native_splash:create
              else
                echo "Splash file is empty or not created, skipping"
              fi
            else
              echo "Failed to download splash, skipping splash configuration"
            fi
          else
            echo "No splash URL provided, skipping splash configuration"
          fi
      
      - name: Build APK
        script: |
          flutter build apk --release \
            --dart-define=GWA_APP_NAME="${GWA_APP_NAME}" \
            --dart-define=GWA_SITE_URL="${GWA_SITE_URL}" \
            --dart-define=GWA_APP_ID="${GWA_APP_ID}" \
            --dart-define=GWA_USER_AGENT="${GWA_USER_AGENT}" \
            --dart-define=GWA_THEME_COLOR="${GWA_THEME_COLOR}" \
            --dart-define=GWA_PLATFORM_ORIENTATION="${GWA_PLATFORM_ORIENTATION}" \
            --dart-define=GWA_SPLASH_BG_MODE="${GWA_SPLASH_BG_MODE}" \
            --dart-define=GWA_SPLASH_BG_COLOR="${GWA_SPLASH_BG_COLOR}" \
            --dart-define=GWA_SPLASH_TAGLINE="${GWA_SPLASH_TAGLINE}" \
            --dart-define=GWA_SPLASH_TEXT_THEME="${GWA_SPLASH_TEXT_THEME}" \
            --dart-define=GWA_SPLASH_DELAY="${GWA_SPLASH_DELAY}" \
            --dart-define=GWA_SPLASH_DISPLAY_LOGO="${GWA_SPLASH_DISPLAY_LOGO}" \
            --dart-define=GWA_SPLASH_BACKGROUND_IMAGE_URL="${GWA_SPLASH_BACKGROUND_IMAGE_URL}" \
            --dart-define=GWA_SPLASH_LOGO_IMAGE_URL="${GWA_SPLASH_LOGO_IMAGE_URL}" \
            --dart-define=GWA_NAV_TYPE="${GWA_NAV_TYPE}" \
            --dart-define=GWA_NAV_ITEMS_B64="${GWA_NAV_ITEMS_B64}"
      
      - name: Build AAB (for Play Store)
        script: |
          flutter build appbundle --release \
            --dart-define=GWA_APP_NAME="${GWA_APP_NAME}" \
            --dart-define=GWA_SITE_URL="${GWA_SITE_URL}" \
            --dart-define=GWA_APP_ID="${GWA_APP_ID}" \
            --dart-define=GWA_USER_AGENT="${GWA_USER_AGENT}" \
            --dart-define=GWA_THEME_COLOR="${GWA_THEME_COLOR}" \
            --dart-define=GWA_PLATFORM_ORIENTATION="${GWA_PLATFORM_ORIENTATION}" \
            --dart-define=GWA_SPLASH_BG_MODE="${GWA_SPLASH_BG_MODE}" \
            --dart-define=GWA_SPLASH_BG_COLOR="${GWA_SPLASH_BG_COLOR}" \
            --dart-define=GWA_SPLASH_TAGLINE="${GWA_SPLASH_TAGLINE}" \
            --dart-define=GWA_SPLASH_TEXT_THEME="${GWA_SPLASH_TEXT_THEME}" \
            --dart-define=GWA_SPLASH_DELAY="${GWA_SPLASH_DELAY}" \
            --dart-define=GWA_SPLASH_DISPLAY_LOGO="${GWA_SPLASH_DISPLAY_LOGO}" \
            --dart-define=GWA_SPLASH_BACKGROUND_IMAGE_URL="${GWA_SPLASH_BACKGROUND_IMAGE_URL}" \
            --dart-define=GWA_SPLASH_LOGO_IMAGE_URL="${GWA_SPLASH_LOGO_IMAGE_URL}" \
            --dart-define=GWA_NAV_TYPE="${GWA_NAV_TYPE}" \
            --dart-define=GWA_NAV_ITEMS_B64="${GWA_NAV_ITEMS_B64}"
    
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab
    
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
      
      # الرفع التلقائي على Google Play (اختياري)
      # لتفعيله: أضف GCLOUD_SERVICE_ACCOUNT_CREDENTIALS في مجموعة google_play
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true

  gwa-ios-build:
    name: GWA iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - gwa_config
        - ios_credentials
      vars:
        GWA_APP_NAME: "Golden WebView App"
        GWA_SITE_URL: "https://example.com"
        GWA_APP_ID: "com.golden.webview.app"
        GWA_THEME_COLOR: "#2196F3"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.golden.webview.app
    
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      
      - name: Update app configuration
        script: |
          cat > assets/config/app_config.json << EOF
          {
            "app_name": "${GWA_APP_NAME:-Golden WebView App}",
            "site_url": "${GWA_SITE_URL}",
            "app_id": "${GWA_APP_ID:-com.golden.webview.app}",
            "user_agent": "${GWA_USER_AGENT:-}",
            "theme_color": "${GWA_THEME_COLOR:-#2196F3}",
            "orientation": "${GWA_PLATFORM_ORIENTATION:-system}",
            "splash_bg_mode": "${GWA_SPLASH_BG_MODE:-color}",
            "splash_bg_color": "${GWA_SPLASH_BG_COLOR:-#2196F3}",
            "splash_tagline": "${GWA_SPLASH_TAGLINE:-}",
            "splash_text_theme": "${GWA_SPLASH_TEXT_THEME:-light}",
            "splash_delay": ${GWA_SPLASH_DELAY:-3},
            "splash_display_logo": ${GWA_SPLASH_DISPLAY_LOGO:-true},
            "splash_background_image": "${GWA_SPLASH_BACKGROUND_IMAGE_URL:-}",
            "splash_logo_image": "${GWA_SPLASH_LOGO_IMAGE_URL:-}",
            "nav_type": "${GWA_NAV_TYPE:-classic}",
            "nav_items": [],
            "permissions": {
              "geolocation": ${GWA_PERM_GEOLOCATION:-false},
              "camera": ${GWA_PERM_CAMERA:-false},
              "microphone": ${GWA_PERM_MICROPHONE:-false}
            },
            "pull_to_refresh": true,
            "enable_javascript": true,
            "clear_cache_on_start": false
          }
          EOF
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      
      - name: Configure app icon
        script: |
          mkdir -p assets/icon
          if [ -n "$GWA_ICON_URL" ] && [ "$GWA_ICON_URL" != "null" ] && [ "$GWA_ICON_URL" != "" ]; then
            echo "Downloading icon from: $GWA_ICON_URL"
            if curl -L "$GWA_ICON_URL" -o assets/icon/app_icon.png --fail --silent --show-error --connect-timeout 30; then
              if [ -f assets/icon/app_icon.png ] && [ -s assets/icon/app_icon.png ]; then
                echo "Icon downloaded successfully"
                echo "" >> pubspec.yaml
                echo "flutter_launcher_icons:" >> pubspec.yaml
                echo "  android: false" >> pubspec.yaml
                echo "  ios: true" >> pubspec.yaml
                echo "  image_path: \"assets/icon/app_icon.png\"" >> pubspec.yaml
                flutter pub get
                flutter pub run flutter_launcher_icons
              else
                echo "Icon file is empty or not created, skipping"
              fi
            else
              echo "Failed to download icon, skipping icon configuration"
            fi
          else
            echo "No icon URL provided, skipping icon configuration"
          fi
      
      - name: Update iOS Bundle ID
        script: |
          BUNDLE_ID="${GWA_APP_ID:-com.golden.webview.app}"
          # Update Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $BUNDLE_ID" ios/Runner/Info.plist
          # Update project.pbxproj
          sed -i '' "s/PRODUCT_BUNDLE_IDENTIFIER = .*;/PRODUCT_BUNDLE_IDENTIFIER = $BUNDLE_ID;/g" ios/Runner.xcodeproj/project.pbxproj
      
      - name: Update iOS App Name
        script: |
          APP_NAME="${GWA_APP_NAME:-Golden WebView App}"
          /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName $APP_NAME" ios/Runner/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleName $APP_NAME" ios/Runner/Info.plist
      
      - name: Build iOS
        script: |
          flutter build ios --release \
            --dart-define=GWA_APP_NAME="${GWA_APP_NAME}" \
            --dart-define=GWA_SITE_URL="${GWA_SITE_URL}" \
            --dart-define=GWA_APP_ID="${GWA_APP_ID}" \
            --dart-define=GWA_USER_AGENT="${GWA_USER_AGENT}" \
            --dart-define=GWA_THEME_COLOR="${GWA_THEME_COLOR}" \
            --dart-define=GWA_PLATFORM_ORIENTATION="${GWA_PLATFORM_ORIENTATION}" \
            --dart-define=GWA_SPLASH_BG_MODE="${GWA_SPLASH_BG_MODE}" \
            --dart-define=GWA_SPLASH_BG_COLOR="${GWA_SPLASH_BG_COLOR}" \
            --dart-define=GWA_SPLASH_TAGLINE="${GWA_SPLASH_TAGLINE}" \
            --dart-define=GWA_SPLASH_TEXT_THEME="${GWA_SPLASH_TEXT_THEME}" \
            --dart-define=GWA_SPLASH_DELAY="${GWA_SPLASH_DELAY}" \
            --dart-define=GWA_SPLASH_DISPLAY_LOGO="${GWA_SPLASH_DISPLAY_LOGO}" \
            --dart-define=GWA_SPLASH_BACKGROUND_IMAGE_URL="${GWA_SPLASH_BACKGROUND_IMAGE_URL}" \
            --dart-define=GWA_SPLASH_LOGO_IMAGE_URL="${GWA_SPLASH_LOGO_IMAGE_URL}" \
            --dart-define=GWA_NAV_TYPE="${GWA_NAV_TYPE}" \
            --dart-define=GWA_NAV_ITEMS_B64="${GWA_NAV_ITEMS_B64}"
      
      - name: Build IPA
        script: |
          xcode-project use-profiles
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --archive-flags="-destination 'generic/platform=iOS'"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
      
      # الرفع التلقائي على App Store (اختياري)
      # لتفعيله: أضف المتغيرات في مجموعة ios_credentials
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
